'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан программой.
'     Исполняемая версия:4.0.30319.42000
'
'     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
'     повторной генерации кода.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Этот класс создан автоматически классом StronglyTypedResourceBuilder
    'с помощью такого средства, как ResGen или Visual Studio.
    'Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    'с параметром /str или перестройте свой проект VS.
    '''<summary>
    '''  Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resourses
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("TimeDictor.Resourses", GetType(Resourses).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Перезаписывает свойство CurrentUICulture текущего потока для всех
        '''  обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _0() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_0", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _1() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_1", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _1_a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_1_a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _10() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_10", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _11() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_11", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _12() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_12", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _13() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_13", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _14() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_14", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _15() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_15", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _16() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_16", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _17() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_17", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _18() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_18", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _19() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_19", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _2() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_2", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _2_a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_2_a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _20() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_20", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _3() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_3", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _30() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_30", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _4() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_4", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _40() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_40", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _5() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_5", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _50() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_50", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _6() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_6", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _7() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_7", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _8() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_8", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property _9() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_9", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property hour() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("hour", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property hour_a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("hour_a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property hour_s() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("hour_s", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property intro_dictor() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_dictor", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property intro_timer() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("intro_timer", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property minute() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("minute", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property minute_a() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("minute_a", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property minute_s() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("minute_s", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property second_s() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("second_s", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  Поиск локализованного ресурса типа System.Byte[].
        '''</summary>
        Friend Shared ReadOnly Property time_end() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("time_end", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
    End Class
End Namespace
